title: Leandro Matias Rivas
logo: /assets/img/matias-foto.jpg
description: "email: rivasleandromatias@gmail.com - Fecha de nacimiento: 29/12/90 - Nacionalidad: argentino - Estado civil: soltero"
theme: jekyll-theme-minimal