title: Leandro Matias Rivas
logo: /assets/img/matias-foto.jpg
description: "Fecha de nacimiento: 29/12/90 - Nacionalidad: argentino - Estado civil: soltero - email: rivasleandromatias@gmail.com"
theme: jekyll-theme-minimal