title: Leandro Matias Rivas
logo: /assets/img/matias-foto.jpg
description: "Edad: 30 años - Fecha de nacimiento: 29/12/90 - Nacionalidad: argentino - DNI: 35974132 - Estado civil: soltero - Domicilio: Humberto Primo 1222 - Código postal: 1103 - Localidad: Constitución - Tel. celular: 1568588176 - email: rivasleandromatias@gmail.com"
theme: jekyll-theme-minimal